Multiple Different Bug Fixes
virtual-labs/comp-code-editor pull request #11
Opened 2024-07-25 19:43 UTC by joeypark743

- Fix input and expected input mismatch
- Fix spacing bug due to CodeMirror
- Implement Feature so Code Output and Expected Output TextBox size can only be changed vertically
- Fix Code Output formatting (used to extract all inputs in array and turn them into string)

2024-07-26 18:10 UTC, raj-vlabs requested changes

2024-07-26 18:10 UTC, raj-vlabs commented on src/App.css
> +.CodeMirror-line {
Instead of changing the value of a predefined class, please use a new class which will override the value specified in CodeMirror-line. I am assuming CodeMirror-line is a class defined in Code Mirror

2024-07-26 18:10 UTC, raj-vlabs commented on src/components/WebEditor/Result.jsx
> +        document.getElementById('expected-result').value = JSON.stringify(${JSON.stringify(exp?.expected)});
Do you need 2 levels of JSON.stringify here? I am not sure I understand this syntax.
Please keep just the minimal necessary code here

2024-07-26 19:18 UTC, joeypark743 commented on src/components/WebEditor/Result.jsx
> +        document.getElementById('expected-result').value = JSON.stringify(${JSON.stringify(exp?.expected)});
So I tried out 

1. `document.getElementById('expected-result').value = JSON.stringify(exp?.expected);`
2. `document.getElementById('expected-result').value = ${JSON.stringify(exp?.expected)};`

separately but the outputs only work when there are 2 levels of JSON.stringify. The first change didn't display the code output at all. The second change caused the same error that we were having with the code output not displaying square brackets. To be completely honest, I am a bit lost on why we need 2 instances of JSON.stringify here as well.

2024-07-26 19:20 UTC, joeypark743 commented on src/App.css
> +.CodeMirror-line {
Implemented this change. Thank you!

2024-07-30 05:51 UTC, raj-vlabs approved these changes

2024-07-30 05:51 UTC, merged